from . import call
from . import channel
from . import channel_message
from . import event
from . import res_partner
from . import res_users
from . import salt_job
from . import server
from . import settings
from . import user
from . import user_channel
from . import web_phone_settings
from . import web_phone_user
